CREATE OR REPLACE TRIGGER SALE_INCREASE
AFTER UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN (OLD.DNAME = 'ACCOUNTING' AND NEW.DNAME = 'SALES')
BEGIN
    -- update salary
    UPDATE IMP
    SET SAL = SAL + 100
    WHERE DEPTNO = :NEW.DEPTNO;
END;
